name: Scheduled Database Backup and Upload

on:
  schedule:
    - cron: '30 19 * * *'  # Runs daily at 1:00 AM IST

jobs:
  backup_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Recreate credentials.json
        env:
          GOOGLE_OAUTH_CREDENTIALS: ${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}
        run: echo "$GOOGLE_OAUTH_CREDENTIALS" > credentials.json

      - name: Recreate token.pickle
        env:
          GOOGLE_OAUTH_TOKEN_BASE64: ${{ secrets.GOOGLE_OAUTH_TOKEN_BASE64 }}
        run: echo "$GOOGLE_OAUTH_TOKEN_BASE64" | base64 --decode > token.pickle

      - name: Run backup script
        run: python backup_db.py

      - name: Upload backup to Google Drive
        run: python upload_to_gdrive_oauth.py
