name: Scheduled Database Backup and Upload

on:
  schedule:
    - cron: '20 13 * * *'  # Runs daily at 13:20 UTC = 6:50 PM IST


jobs:
  backup_and_upload:
    runs-on: ubuntu-latest

    steps:
  - uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

  - name: Reconstruct credentials.json
    env:
      GOOGLE_OAUTH_CREDENTIALS: ${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}
    run: echo "$GOOGLE_OAUTH_CREDENTIALS" > credentials.json

  - name: Run backup script
    run: python backup_db.py

  - name: Upload backup to Google Drive
    run: python upload_to_gdrive_oauth.py
